# Generated by Django 5.0.4 on 2024-05-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_customuser_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_private',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
