# Generated by Django 5.0.4 on 2024-05-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_remove_customuser_is_private_customuser_profile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='user',
            new_name='custom_user',
        ),
    ]
