# Generated by Django 5.0.4 on 2024-05-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
