# Generated by Django 5.0.4 on 2025-01-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_image_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
